server:
  port: 8080

spring:
  application:
    name: jose
  r2dbc:
    url: r2dbc:postgresql://ep-dry-feather-a50464ji.us-east-2.aws.neon.tech:5432/jose?sslmode=require
    username: JG-ChatBot_owner
    password: Qbr4YsUfdz6R
  contentmoderator:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Impvc2UucXVpc3BlMjUwNjIyQGdtYWlsLmNvbSJ9.5P6P6RLYbWPKtSvhXOhx1jdcExvxhA82GJmkg9rNiPg